on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Testing"
        run: ls -a
      - uses: actions/checkout@v3
      - name: "Testing after"
        run: ls -a
      - name: "login docker hub"
        run: docker login --username ${{secrets.USERNAME}} --password ${{secrets.PASSWORD}}
      - name: "Build image"
        run: docker build -t ${{secrets.USERNAME}}/fatmashaaban040170lab .
      - name: "pushing to docker"
        run: docker push ${{secrets.USERNAME}}/fatmashaaban040170lab